name: SOMOS DEVS - DEPLOY

on:
  push:
    branches:
      - master

jobs:
  noop:
    name: Dokploy handles deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Info
        run: echo "Deploy realizado pelo Dokploy"
